{
    'name': 'Odoo K8s SaaS — Subscription Bridge',
    'version': '18.0.1.13.0',
    'summary': 'Links subscription_oca lifecycle to SaaS instance provisioning',
    'category': 'Technical',
    'author': 'AEI Software',
    'license': 'LGPL-3',
    'depends': ['odoo_k8s_saas', 'subscription_oca', 'portal', 'website_sale'],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rules.xml',
        'data/products.xml',
        'data/mail_template_dunning.xml',
        'data/mail_template_renewal.xml',
        'data/subscription_templates.xml',
        'data/ir_cron.xml',
        'data/website_checkout_config.xml',
        'data/website_b2b_enable.xml',
        'views/saas_instance_views.xml',
        'views/sale_subscription_views.xml',
        'views/subscription_template_views.xml',
        'views/subscription_portal_templates.xml',
        'views/checkout_address_override.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'odoo_k8s_saas_subscription/static/src/js/cart_warning.js',
            'odoo_k8s_saas_subscription/static/src/css/portal_aei.css',
        ],
    },
    'installable': True,
    'auto_install': True,
    'application': False,
}
